debug

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -403,15 +403,16 @@ jobs:
           ./gradlew :lua51:publishMavenPlatformPublicationToMavenLocal -PskipSigning -PpublishOnlyDesktop=true
       - name: Verify local Maven publication
         run: |
-          echo "Listing lua51 artifacts in local Maven repository:"
-          ls -lR $HOME/.m2/repository/party/iroiro/luajava/lua51/ || echo "lua51 artifacts not found"
-          echo ""
           echo "Listing all luajava artifacts:"
           ls -lR $HOME/.m2/repository/party/iroiro/luajava/ || echo "luajava artifacts not found"
+          echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
           echo "(org.infinispan) Listing infinispan-lua51 artifacts in local Maven repository:"
-          ls -lR $HOME/.m2/repository/org/infinispan/ || echo "infinispan artifacts not found"
-          ls -lR $HOME/.m2/repository/org/infinispan/infinispan-lua51-platform/ || echo "lua51 artifacts not found"
-          cat $HOME/.m2/repository/org/infinispan/infinispan-lua51-platform/1.2.3-SNAPSHOT/*.pom || echo "no POM"
+          ls -lR $HOME/.m2/repository/io/github/rigazilla || echo "infinispan artifacts not found"
+          echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
+          ls -lR $HOME/.m2/repository/io/github/rigazilla/infinispan-lua51-platform/ || echo "lua51 artifacts not found"
+          echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
+          cat $HOME/.m2/repository/io/github/rigazilla/infinispan-lua51-platform/${VERSION}/*.pom || echo "no POM"
+          echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
